markdown: kramdown

ga_analytics: UA-75884732-1

name: BeautyinFull

url: http://beautyinfull.com

sass:
  style: compressed

menus:
  - name: Beauty & Make-up
    children:
      - name: Skin care
        url: care
  - name: Fashion & Style
    children:
      - name: Skin cere
        url: cere
  - name: Fitness & Health
    children:
      - name: Skin cire
        url: cire
  - name: Inspirations
    children:
      - name: Skin core
        url: core
  - name: Photography
    children:
      - name: Skin cure
        url: cure

exclude:
  - bin/*
  - README.md
