markdown: kramdown

sass:
  style: compressed

t:
  en:
    home:
      name: "Home"
      url: "/"
    about:
      name: "About"
      url: "/about/"
  pt:
    home:
      name: "Casa"
      url: "/casa/"
    about:
      name: "A respeito"
      url: "/a-respeito/"
